version:"3"
services:
  frontend:
    container_name: client-container
    build: /contact-frontend
    ports: 
      - "5173:5173"
    depends_on:
      - backend
    
  backend:
    container_name: backend-container
    build: /contact-backend
    ports:
      - "3000:3000"
