version: "3"
services:
  frontend:
    container_name: client-container
    build: ./contact-frontend
    ports: 
      - "5173:5173"
    environment:
      - API_URL=http://localhost:3000/
    depends_on:
      - backend
    
  backend:
    container_name: backend-container
    build: ./contact-backend
    restart: always
    ports:
      - "3000:3000"
