version: "3"
services:
  frontend:
    container_name: client-container
    build: ./contact-frontend
    ports: 
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - my-network
    
  backend:
    container_name: backend-container
    build: ./contact-backend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - my-network
      
networks:
  my-network:
    driver: bridge
